export enum City {
    Taiwan,
    Taipei,
    NewTaipei,
    Taoyuan,
    Taichung,
    Tainan,
    Kaohsiung,
    Keelung,
    Hsinchu,
    HsinchuCounty,
    MiaoliCounty,
    ChanghuaCounty,
    NantouCounty,
    YunlinCounty,
    ChiayiCounty,
    Chiayi,
    PingtungCounty,
    YilanCounty,
    HualienCounty,
    TaitungCounty,
    KinmenCounty,
    PenghuCounty,
    LienchiangCounty,
}

export enum CardCategory{
    Hotel,
    Activity,
    Scene,
    Food,
}
